### ISSUE TITLE
IntelliJ shows target selection dialog incorrectly

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#1]
having the following configuration
```json
{"target": {"deployment": "b"}}
```
shows dialog, since it expects path to have something while actually it can be like above.

**Comment by Razz4780** [comment]
According to config docs, `target` can be specified either as
```json
{
  "target": "kind/name"
}
```
or
```json
{
  "target": {
    "path": "kind/name"
  }
}
```
In #40 I handle both

**Comment by aviramha** [comment]
@Razz4780 Just to verify, it can also be
```json
{
"target": {"path": {"pod": "podpod"}}
}
```

**Comment by Razz4780** [comment]
Ah, right. This case is handled as well
