### ISSUE TITLE
Make mirrord state more clear

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#100]
User can understand from the UI if mirrord is activated by the background being changed, but it's a very light change and many users miss it.
We need to find out to better display the state.

**Comment by t4lz** [comment]
Maybe we could have different icons for when it's enabled and disabled.
Like maybe a curtain covering the mirror when its disabled. Or if it's possible to see eyes on the tiny icon we could have the eyes from the actual logo when mirrord is enabled, and the eyes could be closed, sleeping, when it's disabled. But I guess the icon is probably too small for that.

**Comment by eyalb181** [comment]
See new icons below:

![v7](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/fbcb2af0-c978-4692-929f-ca0bc8d04c95)
![v8](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/67e02d1a-6251-42f3-b73a-edc9d87ce837)

**Comment by meowjesty** [comment]
I would suggest changing the shape of the little circle, the change in color only is not very obvious (which of the 2 is running/stopped?), and might be hard to see depending on the user's theme.

**Comment by meowjesty** [comment]
I'm colorblind, both are green to me lol.

**Comment by infiniteregrets** [comment]
> I'm colorblind, both are green to me lol.

i see, the debug button changes shape when you start a session, maybe we could do the same?

**Comment by aviramha** [comment]
> I'm colorblind, both are green to me lol.

How about green dot (enabled) and no dot (disabled)?

**Comment by meowjesty** [comment]
Sounds better than just changing color.

I think good UI always changes shapes + colors (I would use a play shape for not running, and a stop shape for running though).

**Comment by eyalb181** [comment]
Some new, colorblind-friendly icons:

![Image](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/515d0c7d-bcf0-4cf1-8727-c42c64c3980c)
![Image](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/721abd16-d3da-4ec8-8d41-d70727d60671)
![Image](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/c4df8a68-fb97-4e55-9a38-7db6a459c0f9)
![Image](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/e0efb494-e810-41e2-845c-2ae488a36180)
