### ISSUE TITLE
update happens during execution

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#116]
### Bug Description

Plugin might update the binary while it's being executed, leading to undefined behavior for example running it while it's not chmodded, executing a file while it's being written etc.

### Steps to Reproduce

It's a race condition - the situation is that IntelliJ tries to update while you run.

### Your operating system and version

macOS

### Local process

n/a

**Comment by Razz4780** [comment]
```kotlin
        val tmpDestination = destination.resolveSibling(destination.name + UUID.randomUUID().toString())

        Files.write(tmpDestination, bytes)
        destination.toFile().setExecutable(true)
        Files.move(tmpDestination, destination, StandardCopyOption.REPLACE_EXISTING)
```
Code fragment from binary manager. Shouldn't we be fine with this atomic rename?

**Comment by eyalb181** [comment]
@Razz4780 @infiniteregrets Is this still relevant after your changes around this area? @aviramha given @Razz4780's comment above should we keep it open?

**Comment by infiniteregrets** [comment]
irrelvant to any changes I have made, the rename as pointed by michal is atomic and shouldn't be a problem IMO and if there is no binary or is downloading, the user would of course get an error
