### ISSUE TITLE
Failed to run on RubyMine on macOS

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord-intellij#136]
### Bug Description

A simple hello_world on RubyMine failed to run on the first two tries, with the error:
> could not determine parent directory for mirrord files, project must contain a project file or a workspace file

![](https://cdn.discordapp.com/attachments/966385220775456808/1148919411353321482/image.png)

### Steps to Reproduce

1. Created a new project.
2. Created `hello.rb` with `puts "Hello World"`.
3. Enabled mirrord.
4. Ran.

This failed twice, and on the third run some time later I got the target selection dialog.

### Your operating system and version

MacOS 13.5.1

### Local process

ruby

### Additional Info

This was not reported to happen to any user. To me it happened in a RubyMine running via a gradle `runIde` task that runs my installed RubyMine. I don't know if it reproduces but I didn't want to just ignore it so I opened this issue so that we can maybe have a look at it later if we have time.

**Comment by t4lz** [comment]
Does not reproduce with 
RubyMine 2023.2.3
Build #RM-232.10072.21, built on October 6, 2023

And mirrord plugin 3.55.0 with (probably) mirrord binary 3.71.2

Also did not reproduce when running RubyMine from `runIde` like in the issue.

Should I continue investigating, e.g. by reviewing the code, or leave it at that as long as no user reports encountering this issue, @eyalb181?

**Comment by eyalb181** [comment]
Hey, closing this then, we'll reopen if anyone encounters it again.
