### ISSUE TITLE
Add a configuration setting to disable auto-update

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-intellij#140]
Since some corporate users can't auto-update their agent, auto-updating the client can cause breakages for them. 
Add a separate config value where they can specify the exact version they want their IDE to download - an empty value meaning just use whatever's there at the moment.
If no CLI has been downloaded and auto-update is disabled, download the latest version.

**Comment by infiniteregrets** [comment]
before I start to work on it I want to know if I have the requirements right:
- Is it a UI feature or supposed to be a part of the mirrord.json config file, whats the exact specification?
- how would the user know what versions are available?
- do we want the user to somehow know what version they currently are on?
- currently, is the cli downloaded regardless of it being in the path if a higher version is available?

**Comment by eyalb181** [comment]
So you just have to add two settings. These are IDE settings, not mirrord.json settings. You don't have to add them anywhere in the UI, they'll just show up wherever the IDE displays extension settings by default.
Expected behavior:
* If the binary path is set, just use that.
* If auto update is set to true (or not set to anything - true should be the default value), keep current behavior (update to latest version)
* If auto update is set to false and a version is set - download that version (if it hasn't already been downloaded)
* If auto update is set to false, no version is set, and no CLI has been downloaded - download the latest version
