### ISSUE TITLE
Quarkus Run Configuration on Windows with WSL does not work

### ISSUE THREAD

**Issue by 0x442E472E** [metalbear-co/mirrord-intellij#148]
### Bug Description

I have a Quarkus 3.2.3.final project that is using Maven 3.9.4. The Run Configuration is of Type "Quarkus" with an Ubuntu 20.04 running with WSL as run target. I'm using Intellij Ultimate 2023.2.1

When i try to execute that Run Configuration, i get the error message `mirrord failed` in the build tab and a pop-up says `can't use on Windows without WSL`.

### Steps to Reproduce

1. Create and download a sample Quarkus project: https://code.quarkus.io/
2. Import the downloaded project as a Maven project in Intellij
3. Intellij should create a Run Configuration. Set the run target to WSL
4. Enable mirrord using the toolbar button
5. Start the Run Configuration

### Your operating system and version

Windows 10 22H2, WSL with Ubuntu 20.04, Plugin Version 3.54.3

### Local process

"Quarkus" Run Configuration

**Comment by eyalb181** [comment]
Duplicates #149
