### ISSUE TITLE
Can't run with steal mode without specifying target in config file

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-intellij#162]
### Bug Description

When I create a config file with incoming.mode = steal and no target specified, I get an error (Can't run targetless with steal mode), where I should be getting the target selection dialog.
Probably happens in VS Code as well.

### Steps to Reproduce

See above.

### Your operating system and version

N/A

### Local process

N/A

**Comment by meowjesty** [comment]
Fixed by [#1965](https://github.com/metalbear-co/mirrord/pull/1965).
