### ISSUE TITLE
Incorrect outdated version warning

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord-intellij#163]
### Bug Description

Sometimes I get a warning saying my version is outdated - this has no effects with the way disable autdownload/execution works. However it probably happens how I set the version in the previous PR for adding the disable autodownload option.

### Steps to Reproduce

Just close and run again.

### Your operating system and version

macos

### Local process

go

**Comment by eyalb181** [comment]
@infiniteregrets Do you know when you get the incorrect warning?

**Comment by infiniteregrets** [comment]
> @infiniteregrets Do you know when you get the incorrect warning?

This was fixed in the binary download improvements
