### ISSUE TITLE
IDE hangs then fails

### ISSUE THREAD

**Issue by mdemianenko** [metalbear-co/mirrord-intellij#170]
### Bug Description

Hello!

I am running a kotlin project with gradle. When using the default run/debug config of intellij idea, the IDE hangs for 2-3 minutes and then errors out with:
![image](https://github.com/metalbear-co/mirrord-intellij/assets/146939305/4632f33a-d84a-4137-b0d1-e85b49c64446)

If I use gradle task in the run/debug config, plugin works

My mirrord conifg:
```
{
  "operator": false,
  "target": {
    "path": {
      "deployment": "my-deploy"
    }
  },
  "feature": {
    "fs": {
      "mode": "localwithoverrides"
    },
    "network": {
      "incoming": {
        "mode": "steal",
        "ignore_localhost": true,
        "port_mapping": [
          [50051, 50051],
          [8080, 8080]
        ],
        "ignore_ports": [
          9001
        ]
      },
      "outgoing": {
        "ignore_localhost": true
      }
    }
  },
  "agent": {
    "log_level": "mirrord=trace,warn",
    "image": "ghcr.io/metalbear-co/mirrord:3.70.0",
    "ttl": 30,
    "ephemeral": false,
    "communication_timeout": 30,
    "startup_timeout": 360,
    "network_interface": "eth0",
    "flush_connections": true
  }
}
```

Mirrord cli/agent version: 3.70.1
OS: 
<img width="206" alt="image" src="https://github.com/metalbear-co/mirrord-intellij/assets/146939305/d3c93e20-c571-464e-91a9-b932a3acc4af">

### Steps to Reproduce

See the bug description

### Your operating system and version

Mac pro 2021, ventura 13.5.2 

### Local process

./gradlew server:run --debug-jvm

**Comment by meowjesty** [comment]
Wasn't able to reproduce this on linux.

Tried a new kotlin project created from Intellij Idea Ultimate, with the config provided by @mdemianenko (changing the target to one of my deployments), and the hanging doesn't occur.

If I add the `--debug-jvm` args to the runner command line, mirrord doesn't run the sample app though, it's running something else (maybe gradle? not sure), and the "Run" window keeps showing spinning progress as if the `:run` task is never finished (IDE remains responsive though).

Could you please provide some more information, like JDK, kotlin version, a sample project with all of this already setup would be incredibly helpful as well.

**Comment by eyalb181** [comment]
Hey @mdemianenko, could you please provide the required information?
