### ISSUE TITLE
IDE freezes (until timeout) if you set `MIRRORD_IMPERSONATED_TARGET` env var in a java project with an invalid config.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord-intellij#182]
### Bug Description

Long title, but that's what happens. If you set `MIRRORD_IMPERSONATED_TARGET` in the launcher options thingy for a java project, and the `mirrord.json` config file contains an error (missing comma is enough to trigger), then the IDE freezes until the timeout of 2 minutes is reached.

https://github.com/metalbear-co/mirrord-intellij/blob/1652125fb763e0b845f2546a14362a5959fcb19e/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt#L422-L432

It only happens in java projects, but I'm not sure if it happens in different JVM projects, like kotlin samples, or even in different java project settings (my sample uses gradle, but don't know if maven also triggers it).

### Steps to Reproduce

1. Create a java project in Intellij Idea (I'm using the Community version);
2. Set up mirrord config with a `target` (java projects can't show the selection dialog for it), and a typo somewhere (add an extra comma, or remove one);
3. Go into the launcher settings, and add `MIRRORD_IMPERSONATED_TARGET={some-pod}`;

### Your operating system and version

linux

### Local process

intellij with java "hello, world" sample

**Comment by eyalb181** [comment]
Retested, was fixed by verify-config
