### ISSUE TITLE
Tomcat app not working on IDEA

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-intellij#183]
### Bug Description

When a user tried running a Tomcat server in IDEA, it started properly but couldn't receive incoming traffic.

### Steps to Reproduce

N/A

### Your operating system and version

N/A

### Local process

N/A

**Comment by Razz4780** [comment]
I need some reproduction steps to proceed. Do we know which Tomcat plugin is used to run the project?
