### ISSUE TITLE
IntelliJ executes mirrord twice in Gradle based runs on Kotlin

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#210]
When running IntelliJ on macOS with a ~Kotlin based project and Gradle~ Scala project with `Application` run configuration type,  mirrord executes twice, leading to undefined experience.
Also causes agent to be stuck as long as gradle daemon is ran

**Comment by t4lz** [comment]
Trying to reproduce in https://github.com/t4lz/gradle-play-scala-application/tree/main
That repo isn't working yet, can't even run without mirrord.
