### ISSUE TITLE
Debug Java Application in IntelliJ leads to "Cannot load JVM TI agent twice" error

### ISSUE THREAD

**Issue by vsfku** [metalbear-co/mirrord-intellij#218]
### Bug Description

IntelliJ mirrord plugin version: 3.56.2

When trying to start a Java application in IntelliJ with the Mirrord IntelliJ plugin active, leads to the problem that the application fails to start with the following error message:
`
.../java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:46177,suspend=y,server=n -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dmanagement.endpoints.jmx.exposure.include=* -javaagent:/home/.../.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/plugins/java/lib/rt/debugger-agent.jar -Dfile.encoding=UTF-8 -classpath ...
Error occurred during initialization of VM
agent library failed to init: jdwp
Picked up JAVA_TOOL_OPTIONS: -Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
`

### Steps to Reproduce

1. Create a simple Java project in IntelliJ with Spring Initializr (Language: Java, Type: Gradle - Groovy)
2. Activate mirrord in IntelliJ
3. Start the Application.java in debug mode
-> Applications fails to start
Deactivate mirrord in IntelliJ: Applications starts in debug mode

### Your operating system and version

Windows 11 WSL2 21H2

### Local process

IntelliJ

**Comment by aviramha** [comment]
Hey! Thanks for reporting this. I suspect this happens due to duplicate env being fetched from the remote pod - you can probably remove the local env or exclude the remote one using 
```json

"env": {"exclude": ["JAVA_TOOL_OPTIONS"]}
```

**Comment by vsfku** [comment]
Hello,
thanks for the fast response.
This fixed my problem.

**Comment by aviramha** [comment]
You're welcome! If you like mirrord we'd appreciate a review in the marketplace :)
