### ISSUE TITLE
Use BeforeRunTaskProvider for Tomcat

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord-intellij#230]
~~We asked for it here: https://youtrack.jetbrains.com/issue/IDEA-342485/Expose-a-Tomcat-RunConfigurationExtension~~

currently there isn't one so we have an `ExecutionListener` for Tomcat where we have to detect Tomcat runs by the dynamic type of the configuration.

**Comment by eyalb181** [comment]
Hey @t4lz , @Razz4780 I saw you discussed this in the JetBrains issue tracker - can this issue be closed?

**Comment by t4lz** [comment]
> Hey @t4lz , @Razz4780 I saw you discussed this in the JetBrains issue tracker - can this issue be closed?

Updated issue title and comment. @aviramha asked me to open this issue because our detection of Tomcat runs is a bit weird. JetBrains provided an existing solution, what we asked for isn't necessary. @Razz4780 said we can use `BeforeRunTaskProvider` for this.
