### ISSUE TITLE
Add env check for enabling mirrord explicitly via run configuration

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#231]
If user sets `MIRRORD_ACTIVE=1` in their run configuration's environment, mirrord should run even if button is disabled.

**Comment by t4lz** [comment]
How about also accepting `MIRRORD_ACTIVE=0` to disable mirrord for a run configuration even if the button is enabled?

**Comment by aviramha** [comment]
@t4lz I actually thought about it but felt like it's an over kill - they should just ignore the button and use the explicit for on always, not having means off for them.. but if user asks maybe I'll think about it again..
