### ISSUE TITLE
IDE shows warning regarding support for multipod deployments while using the operator.

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord-intellij#235]
> When targeting multi-pod deployments, mirrord impersonates the first pod in the deployment. Support for multi-pod impersonation requires the mirrord operator, which is part of mirrord for Teams.

This warning should not be shown while the operator is in use.

**Comment by aviramha** [comment]
Need to add new env for this to work

**Comment by aviramha** [comment]
Fixed in #252
