### ISSUE TITLE
automatically start/stop the mirrord agent when running Execution Configurations?

### ISSUE THREAD

**Issue by jstrachan** [metalbear-co/mirrord-intellij#241]
mirrord is an excellent tool; I’m really impressed with it! here's a suggestion for making the developer UX even slicker & I'm happy to try create a patch if you think it makes sense...

what I’ve found is that my IntelliJ projects tend to have a lots of different Execution Configurations I save/run randomly of either form:

* a relatively small number of, say, golang binaries that run microservices which I want to use the mirrord agent to run them effectively inside k8s
* lots of unit / integration tests / other tasks I run from time to time from IntelliJ

currently as I’m switching between Execution Contexts (e.g. a mirrord service versus a unit/integration test/non-k8s binary) I need to remember to enable/disable the mirrord agent whenever switching between k8s/non-k8s executions.

I’d like to be able to add a feature to the mirrord intellij plugin so that we can configure an Execution Context to lazy-run the mirrord agent on demand. So I can enable the lazy-run mirrord option for the agent on the relatively small number of Execution Context processes I want to use mirrord for; and default to off for the zillions of test cases in the codebase. It would then start the agent if its not running, run the process as today - then on termination, stop the agent again (maybe with some quiet period)

i.e. I’d like to avoid having to remember to press the enable/disable mirrord button in IDEA  its easy to forget then things tend to break if you haven’t got the agent when you need it - or its running when you don’t want it to run etc. I

then mirrord would work like magic and I can run/debug anything and IntelliJ would do the right thing; (once I’ve enabled lazy-run on the few k8s based Execution Contexts)

do you think this feature seems feasible? I’ll happily take a stab at trying to implement it - I’m hoping its just a pre-post hook that checks for the new lazy-run configuration option on the Execution Configuration and effectively starts/stops the agent?

**Comment by aviramha** [comment]
Hey!
Thanks for the kind words.
We actually support something that I think solves your use case - you can add `MIRRORD_ACTIVE=1` as env in your run configuration, and it will use mirrord even if not active via the toggle button.
Let me know if that solves your case!

**Comment by aviramha** [comment]
@jstrachan Can we close this then?

**Comment by jstrachan** [comment]
sorry for the delay getting back to you. The `MIRRORD_ACTIVE=1` environment variable works perfectly for my use case - many thanks!
