### ISSUE TITLE
Add support for uvicorn

### ISSUE THREAD

**Issue by playdaddy** [metalbear-co/mirrord-intellij#248]
Not sure if it's a feature or bug...

I'm trying to run very basic fastapi project to evaluate mirrord.
I'm using Pycharm, local kind cluster and run application with uvicorn.
Here is the code I use https://github.com/adimentech/fastapi-mirrord

When I use fastapi configuration template to run/debug my application, mirrord starts with no issues, but doesn't mirror or steal remote traffic.

When I changed app to run uvicorn from app itself 
```
if __name__ == "__main__":
    uvicorn.run("main:app", port=8000, log_level="info")
```

mirrord started to work as expected

Python configuration screenshot
<img width="932" alt="Screenshot 2024-03-16 at 21 21 47" src="https://github.com/metalbear-co/mirrord-intellij/assets/159779630/257de27e-dd38-4834-adb0-f0b60597e80e">

Fastapi configuration template
<img width="926" alt="Screenshot 2024-03-16 at 21 42 50" src="https://github.com/metalbear-co/mirrord-intellij/assets/159779630/ed3d0f49-c6c3-4fc4-b2fd-d431bc5970f4">

**Comment by aviramha** [comment]
Thanks for reporting this. We have a known, open issue about uvicorn + reload. Can you try to remove reload and see if it works for you?
https://github.com/metalbear-co/mirrord/issues/864

**Comment by playdaddy** [comment]
Thanks. Without `--reload` it works fine.
For me it's enough.
