### ISSUE TITLE
Plugin runs the wrong configuration

### ISSUE THREAD

**Issue by ewhauser** [metalbear-co/mirrord-intellij#257]
### Bug Description

When using the mirrord plugin in Goland, I go to a main method and select "Run" using the play button on the sidebar. I find that if I am switching between services, the plugin often runs the Run configuration that I was previously using vs. the current one I am selecting. If I then go run it again, it runs the correct one.

### Steps to Reproduce

1. Enable mirrord using the toolbar icon
2. Run a service using it's main
3. Stop the session
4. Go to a new service and run it's main (you should see that it runs the previous service here)
5. Stop the session
6. Run the same service again (it should use the right configuration this time)

### Your operating system and version

MacOS 14.3

### Local process

Any Go program under the IDE

### Local process version

GoLand 2024.1

**Comment by aviramha** [comment]
Thanks for reporting this.
At first glance, it sounds like a GoLand bug rather than mirrord, since mirrord doesn't modify/touch the actual run configuration nor run the service by itself (it does interact with it)
Can you check if this happens even without mirrord installed/enabled?

**Comment by ewhauser** [comment]
It does not happen when `mirrord` is disabled. It is reproducible every time.

**Comment by aviramha** [comment]
Couldn't reproduce on older GoLand. Trying same version as issue.

**Comment by aviramha** [comment]
Couldn't reproduce on latest as well - attaching screen recording to confirm that I'm trying to reproduce correctly.


https://github.com/metalbear-co/mirrord-intellij/assets/41201924/f5b8351e-93b7-4f90-89ce-05d4f5600005

**Comment by ewhauser** [comment]
Closing this for now as I'm unable to reproduce with the latest version of Goland
