### ISSUE TITLE
when json is invalid mirrord just fails without any descriptive error

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#261]
```json
{
  "operator": true,
  "target": {
    "path": "deployment/X",
    "namespace": "X"
  },
  "feature": {
    "network": {
      "incoming": {
        "mode": "steal",
        "port_mapping": [
          [
            8077,
            8080
          ]
        ],
        "http_filter": {
          "header_filter": "x-X-subject: {{ get_env(name='X_USER_ID') }}",
          "port": [8080, 8077]
        }
      }
    },
    "fs": "read",
    "env": {
      "include": "SECURITY_JWT_*;SPRING_DATASOURCE_*"
    }
  }
}
```

**Comment by meowjesty** [comment]
![image](https://github.com/metalbear-co/mirrord-intellij/assets/43983236/ec1f2a83-358e-442f-b2d9-03c31884ba7a)

It actually shows 3 errors, but this one is the most relevant.

I'll work on improving the message, using the new message API we have.

**Comment by meowjesty** [comment]
![image](https://github.com/metalbear-co/mirrord-intellij/assets/43983236/192f31ce-b852-48d0-92af-5560a7024d5f)

Better (this should apply to both intellij and vscode)?

**Comment by aviramha** [comment]
Important to note that the user had the env set, so it wasn't a templating error (it was `port` instead of `ports`)
so maybe we have more than one issue here?

**Comment by meowjesty** [comment]
![image](https://github.com/metalbear-co/mirrord-intellij/assets/43983236/6fa47bcf-43c1-4c11-a2c6-7f2b639b2c81)


What I got when setting `X_USER_ID=boo` in the env vars. Am I still missing something?

**Comment by aviramha** [comment]
maybe old extension then :@

**Comment by aviramha** [comment]
or maybe the mirrord failed error took over and somehow this was hidden?

**Comment by meowjesty** [comment]
> mirrord failed error took over 

Yeah, I think this might be it. When a config error happens I see 3 error dialogs popping up. So maybe the more interesting ones closed before the user saw those?

**Comment by meowjesty** [comment]
It would be nice to have this just use the new messages API, where we can control all of this from the cli, and thus just show 1 error, but as this is ran as part of `verify-config` it's a bit more troublesome than just taking the progress output.

**Comment by meowjesty** [comment]
Could not really reproduce this.
