### ISSUE TITLE
Mirrord opens the config file from another open project.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord-intellij#27]
### Steps to Reproduce

1. Open a project with a mirrord config file in a pycharm window.
2. Create a new project in a new PyCharm window.
3. Click on the config file symbol.
4. The config file from the other project opens in the new project.

### Your operating system and version

Linux

**Comment by eyalb181** [comment]
@Razz4780 Have a look at this when you work on the config dropdown for IntelliJ please
