### ISSUE TITLE
Tomcat runs mirrord twice, incompatible with scaledown

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#280]
### Bug Description

when user uses tomcat they get the mirrord launch triggered twice for some reason - this isn't so bad, unless using scaledown then one fails because of conflict

### Steps to Reproduce

couldn't reproduce
IntelliJ IDEA 2023.1.6
Tomcat 7.0.105

### Your operating system and version

macos

### Local process

tomcat

**Comment by aviramha** [comment]
This issue also happens with tasks that happen before launch, triggering another plugin entrypoint.
Perhaps we should add a check if env for mirrord is already set, and if so, skip?

**Comment by DmitryDodzin** [comment]
@aviramha Do we want to prevent the execution from the plugin or should the cli be able to be called exec twice where only the first execution creates agent and intproxy and second one reuses them?
