### ISSUE TITLE
Not closing the agent and not mirroring/stealing the traffic

### ISSUE THREAD

**Issue by sandeepcmsm** [metalbear-co/mirrord-intellij#281]
### Bug Description

After updating to latest goland version, mirror agent stopping terminating the agent job running on k8s.
i have tried this in run and debug mode. i can see lot of mirrord deamon process keep running on my mac os. 
so i manually keep killing them so it will close the jobs. 

after the process started, i dont see mirror of the http traffic happening. 

then i tried the same with visual studio code, everything works fine there. 

mirrord version: 3.116.3

my k8s cluster does not have sidecars. i'm connected to my office vpn using openvpn from home network. 
k8s cluster can be accessed using only whitelisted vpn ip.

Goland configuration as fallows:
GoLand 2024.2.1.1
Build #GO-242.21829.220, built on September 8, 2024
Licensed to Sandeep CS
Subscription is active until December 5, 2024.
Runtime version: 21.0.3+13-b509.11 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=777777
  editor.focus.mode.color.dark=777777
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.tasks (242.20224.204)
  com.fobgochod (2022.3.5)
  com.mroche.JsonHelper (1.3.2)
  com.markskelton.one-dark-theme (5.11.0)
  net.sjrx.intellij.plugins.systemdunitfiles (223.240904.242)
  String Manipulation (9.14.1)
  color.scheme.Panda Syntax (0.4)
  ChatGPT (3.3.6-241.242)
  org.toml.lang (242.20224.155)
  com.intellij.ml.llm (242.21829.196)
  org.jetbrains.plugins.vagrant (242.20224.159)
  com.intellij.nativeDebug (242.21829.165)
  com.nasmlanguage (0.6-beta.1)
  com.metalbear.mirrord (3.61.2)
  com.ypwang.plugin.go-linter (1.6.6)

### Steps to Reproduce

install GoLand 2024.2.1.1
install latest mirrord plugin. 
debug the any sample go program.

### Your operating system and version

mac os 14.6.1

### Local process

golang process: using delve and normal process run name is qbs

**Comment by aviramha** [comment]
Thanks for reporting. I will try to reproduce.

**Comment by aviramha** [comment]
Can't reproduce. I'm not sure what is going on. Would you like to schedule a support session to share screen?

**Comment by aviramha** [comment]
Waiting for your input

**Comment by sandeepcmsm** [comment]
We can connect at 9 30 PM IST. I can show you.

**Comment by aviramha** [comment]
@sandeepcmsm I can do one hour later if you'd like - share your email so I can send an invite.

**Comment by aviramha** [comment]
When downgrading to previous version, debug failed due to the delve patch - we should probably make this patch only if go plugin version is old
The patch didn't help the new version though
go 1.23, delve latest,

**Comment by aviramha** [comment]
I fear that might be a new GoLand + x64 thing since it doesn't reproduce to me.
can you share how you installed Go? @sandeepcmsm

**Comment by sandeepcmsm** [comment]
I use the jetbrains toolbox to install it.

**Comment by aviramha** [comment]
@sandeepcmsm does this still happen?
