### ISSUE TITLE
Debugging gradle tasks does not work

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord-intellij#290]
In intellij you can [run or debug gradle tasks](https://www.jetbrains.com/help/idea/work-with-gradle-tasks.html#gradle_tasks)

![image](https://github.com/user-attachments/assets/f120c604-4b8f-49d8-a8b2-11b4f87886b9)

For projects that are organized with gradle this looks and feels almost the same pressing the normal Run or Debug buttons, but it isn't.

A user has a project that is executed with the [bootRun task](https://docs.spring.io/spring-boot/gradle-plugin/running.html), and running that gradle task works, but debugging that gradle task did not (that task just takes for ever).

Debugging normally (not via the gradle sidebar - Ctrl + D vs. Ctrl + Shift + D), works.

**Comment by Razz4780** [comment]
Which plugin and mirrord binary versions were used? I'm failing to reproduce with plugin 3.63.0 and 3.121.0. I've debugged my task successfully multiple times

**Comment by t4lz** [comment]
Latest at the time, so I think 3.62.1 + 3.120.1.
It's possible it only happens with some tasks.

**Comment by Razz4780** [comment]
I've tried 3.62.1+3.120.1, successfully ran and debugged some random Gradle tasks (including `bootRun`). I think we need user input on this one
