### ISSUE TITLE
IntelliJ plugin: mirrord dropdown menu in toolbar cannot be interacted with on WSL

### ISSUE THREAD

**Issue by gememma** [metalbear-co/mirrord-intellij#297]
When using IntelliJ in remote development mode, the dropdown menu cannot be clicked on or selected. This issue does not occur when the plugin is built locally and opened with the runIde task, nor when used in non-remote dev mode on Windows.

**Comment by gememma** [comment]
When you open the IDE in remote development mode, you can either install plugins on the host or the client. For mirrord, it makes sense that you need to install on the host since it needs access to the things in WSL (like kubectl) but something like the dropdown menu may not be able to run properly in the headless IDE that runs on the host.

My current working theory is that the mirrord plugin works when you build locally AND when you open intellij in regular mode instead of remote dev because its using the non-headless IDE.

**Comment by gememma** [comment]
There is a workaround for this issue: mirrord seems to work fine when the plugin is only installed on the host, and to access the dropdown menu you can open the UI of the host backend (see instructions here [https://www.jetbrains.com/help/idea/work-inside-remote-project.html#access_backend_settings](https://www.jetbrains.com/help/idea/work-inside-remote-project.html#access_backend_settings)) and use it from the new window - note that this may open tabs in the original (frontend) window.

**Comment by Razz4780** [comment]
I was not able to reproduce the issue. Once I properly set up everything, dropdown menu worked just fine. I tested both:

1. mirrord only on host (is it strange that I could still use mirrord UI in this case?)
2. mirrord both on host and on client
