### ISSUE TITLE
Multiple configuration files don't work in IntelliJ

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#3]
While working with a user I noticed that creating another file ending with `mirrord.json` didn't work and didn't display the dropdown menu. We also tried restarting the IDE and it didn't help.

**Comment by eyalb181** [comment]
@Razz4780 Have a look at this when you work on the config dropdown for IntelliJ please

**Comment by infiniteregrets** [comment]
This issue here is that the config file needs to be project specifc, should be a very small fix
