### ISSUE TITLE
mirrord config dialog shows ".../.mirrord/mirrord.json"

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#311]
mirrord config dialog shows ".../.mirrord/mirrord.json"
I believe we add an extra `.`?

**Comment by Razz4780** [comment]
> mirrord config dialog shows ".../.mirrord/mirrord.json" I believe we add an extra `.`?

This is on purpose, `...` stands for project root dir. This path is produced by intellij util function `calcRelativeToProjectPath`. I guess this is the standard way of showing paths

**Comment by aviramha** [comment]
But then users try to use it and it doesn't work (I think?) or it's confusing G:

**Comment by Razz4780** [comment]
You mean they copy-paste it to mirrord config? :eyes:

**Comment by aviramha** [comment]
They copy paste it as value for `MIRRORD_CONFIG_FILE`

**Comment by Razz4780** [comment]
tbh I don't know what to think of this...
Maybe we can add a copy-full-path-to-clipboard button?

**Comment by aviramha** [comment]
I mean, I was confused by it and users have no idea that's what `...` means so I'd just strip it if anything from display

**Comment by aviramha** [comment]
i.e make it show `.mirrord/mirrord.json`

**Comment by aviramha** [comment]
I mean, it makes more sense that it'd work :D

**Comment by Razz4780** [comment]
Ok, I'll see if it does

**Comment by Razz4780** [comment]
> I mean, it makes more sense that it'd work :D

This won't work out of the box, because our working directory is not the project root. It's the `bin` subdirectory inside IDE installation directory. It could work if we changed workdir to project root when calling mirrord CLI, but project root is not well defined on this platform (for example, a project might have multiple roots :V)

I suggest displaying in the config dialog either:
1. just absolute paths
2. relative paths in current format (`.../.mirrord/mirrord.json`) with a button that pastes absolute path to clipboard

**Comment by aviramha** [comment]
Are you saying that using the project path wouldn't work? I am not suggesting to use it, but to show it and ignore the copy paste bit (since at least you can realize yourself that the path is different between env vs shown)

**Comment by Razz4780** [comment]
Now I'm lost :V
Can you give an example of what you have in mind?

**Comment by aviramha** [comment]
I think it should show `.mirrord/mirrord.json` with the project path stripped, but underneath yeah use full path..

**Comment by Razz4780** [comment]
But the problem was that the users copy-paste it into runtime config and it wouldn't work, no?
So this would not work either. They'd copy-paste path relative to project root and mirrord would fail

**Comment by aviramha** [comment]
Copy paste is one symptom, but I think having a clearer path that doesn't have magic and makes sense is better.

**Comment by Razz4780** [comment]
Okok, will do
