### ISSUE TITLE
Failure when debugging Spring Boot pod in IntelliJ

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord-intellij#42]
### Bug Description

Debugging a Spring Boot pod in IntelliJ fails.

Worked after a restart.

### Steps to Reproduce

---

### Relevant Logs

```shell
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```
```


### Your operating system and version

---

### Local process

---

### Local process version

_No response_

### Additional Info

_No response_

**Comment by infiniteregrets** [comment]
suggestion solution by IntelliJ folks, haven’t tried 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/12176087844882-Expose-the-debugger-ephemeral-port-before-the-debug-session-starts-in-the-API
