### ISSUE TITLE
Can't use on Windows

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#48]
In the case of using Mirrord (IntelliJ Plugin) on Windows, the plugin fives an error : `Can't use mirrord on Windows without WSL` as stated in #1544 even if I have WSL rinning on my machine.
Is the error message misleading and the feature is not supported at all on windows or I'm I missing something?

_Originally posted by @GMouaad in https://github.com/metalbear-co/mirrord/issues/28#issuecomment-1640107658_

**Comment by GMouaad** [comment]
Hi @aviramha , thank you for the followup. I'm using the initial (unchanged) configuration of the plugin and it looks as the following: 
```Javascript
{
    "accept_invalid_certificates": false,
    "feature": {
        "network": {
            "incoming": "mirror",
            "outgoing": true
        },
        "fs": "read",
        "env": true
    }
}
```
I'm still dicovering MirrorD (and I find the value proposition pretty god btw.) though I didn't find a documentation section on what should be configured when running on windows using WSL. 

Any hints?

**Comment by aviramha** [comment]
You're welcome @GMouaad.
To use mirrord on Windows in IntelliJ you'd need the "Run configuration" to be configured to "Run on" Linux or open the project from the Linux path (`/mnt/c$/path-to-proj` usually). Can you provide the run configuration of IntelliJ you tried using?

**Comment by aviramha** [comment]
Can you try opening the project from the WSL Path?

**Comment by JohnnyFasching** [comment]
I tried open the project with the wsl path, but this is prohibited by windows. It tells you that you are not allowed to open this path in the program.

**Comment by deyanp** [comment]
@aviramha , I am a colleague of @JohnnyFasching and we are using Jetbrains Rider 2023.3.3, with .NET/F# (should be same with C#)

**Comment by aviramha** [comment]
hi @deyanp , either of you are up for a screen share session?
can schedule time here
https://calendly.com/aviram-5/30min

**Comment by deyanp** [comment]
thanks @aviramha! Let us double-check again with these 2 options:

1. https://www.jetbrains.com/remote-development/gateway/
2. vs code supports already starting from WLS2

and get back to you for a screen sharing next week

**Comment by aviramha** [comment]
hey @deyanp - did you get it sorted?
