### ISSUE TITLE
Debugging Spring Boot + Gradle application sometimes fails with panic in tokio

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord-intellij#49]
### Bug Description

The application fails and the following log is produced in the IDE console:
```
thread 'tokio-runtime-worker' panicked at 'Bad read on self-pipe: Bad file descriptor (os error 9)', /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/signal/mod.rs:120:27
```
Does not happen every time, sometimes the application works totally fine.

Not observed when running without the debugger.

### Steps to Reproduce

1. Create a simple Sprint Boot + Gradle app. Example I used:
```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class DemoApplication {
	@RestController
	public static class HomeController {
		@RequestMapping(value = "/")
		public static String welcome() {
			System.err.println("whatever");
			return "whatever";
		}
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```
2. Debug with mirrord enabled
3. Repeat 2. until the app fails to start

### Your operating system and version

Linux 5.19.0-46-generic #47~22.04.1-Ubuntu x86_64 GNU/Linux

### Local process

java: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=283e3424455d4e52e92122e1ec8a2319445076aa, not stripped

### Local process version

openjdk 17.0.7 2023-04-18 LTS

**Comment by eyalb181** [comment]
Seems to have been fixed at some point.
