### ISSUE TITLE
Consider moving extension entrypoints to `ExecutionListener` subclasses

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord-intellij#56]
IntelliJ platform exposes the `ExecutionListener` extension point. It enables listening to executions (scheduled, starting, started, not started, terminated) and manipulating run profiles. It's methods seem to be called always from the dispatch thread, which enables write access and showing dialogs. Consider moving the entrypoints there.

**Comment by eyalb181** [comment]
@Razz4780 Can you elaborate on benefits over the current state?

**Comment by Razz4780** [comment]
When developing `Tomcat` support this way, I found out that we're not able to cancel the execution from the `ExecutionListener` flow. I think this kills the idea. @eyalb181 wdyt?

**Comment by eyalb181** [comment]
Is this only for Tomcat, or in general?

**Comment by Razz4780** [comment]
It's a general limitation

**Comment by eyalb181** [comment]
Then yeah, lets close this for now.
