### ISSUE TITLE
error on pod listing in JetBrains is not clear

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-intellij#6]
When executing program with mirrord on JetBrains with invalid (kubernetes) context/config it shows "mirrord run cancelled" instead of more informative error.

**Comment by aviramha** [comment]
pretty sure this was solved? @Razz4780 @eyalb181

**Comment by Razz4780** [comment]
![Screenshot from 2023-06-26 11-39-50](https://github.com/metalbear-co/mirrord-intellij/assets/34063647/6e45dba9-73d3-440e-85ac-0bb1826a9cae)
This is what's shown when I use malformed config, I believe it was solved
