### ISSUE TITLE
Process not closing when stopping debugger

### ISSUE THREAD

**Issue by jorros** [metalbear-co/mirrord-intellij#67]
### Bug Description

Starting the project in debug mode won't close the process once I stop the debugger. It boots up and works as intended, but the moment I stop it the process keeps on going. I have to manually kill it through terminal.

This only happens when I'm debugging the process, running it without debugger works as expected.

### Steps to Reproduce

1. Create a new dotnet application (e.g. `dotnet new webapp`)
2. Run with debug configuration
3. Stop the debug session
4. Rider signals on the UI that it stopped, but using `ps` you should be able to see the process is still running
5. Terminal connected to application within Rider is still showing new logs coming from running app

### Your operating system and version

macOS 13.4.1

### Local process

/usr/local/share/dotnet/dotnet: Mach-O 64-bit executable arm64

### Local process version

7.0.102

### Additional Info

mirrord config:
`{
    "accept_invalid_certificates": false,
    "feature": {
        "network": {
            "incoming": "steal",
            "outgoing": true
        },
        "fs": "write",
        "env": true
    }
}
`

**Comment by jorros** [comment]
One thing I have noticed as well is that whilst debugging I'm not able to hit any breakpoints.

**Comment by aviramha** [comment]
Found out that bringing remote env `COMPlus_EnableDiagnostics` both reported issues.

Can be resolved temporarily by having this in the mirrord.json:
```json
        "env": {
            "exclude": ["COMPlus_EnableDiagnostics"]
        }
```

Created #1728 and #1729 to exclude the env and fix it by default :)
