### ISSUE TITLE
Failure when using existing, local binary

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-intellij#70]
### Bug Description

When the binary download fails and we fall back to the local binary, we get the following error:
![image](https://github.com/metalbear-co/mirrord-intellij/assets/5508354/d1f71e87-e14b-43a8-bfc7-52fd06460004)

### Steps to Reproduce

See description.

### Your operating system and version

MacOS

### Local process

N/A

**Comment by Razz4780** [comment]
The error notification looks like config file parsing failure. Do you know which version of the plugin this comes from?
I don't see how this would be possible with the current version, relevant code below:
```
    try {
        val parsed = gson.fromJson(contents, ConfigData::class.java)
        return parsed?.target?.path != null
    } catch (_: Exception) {
    }

    try {
        val parsed = gson.fromJson(contents, ConfigDataSimple::class.java)
        return parsed?.target != null
    } catch (_: Exception) {
        throw InvalidConfigException(configPath, "invalid config")
    }
```

**Comment by aviramha** [comment]
I think it's actually trying to parse the cli stdout/err since the config doesn't have any new fields.

**Comment by Razz4780** [comment]
> I think it's actually trying to parse the cli stdout/err since the config doesn't have any new fields. It comes from latest release.

That was actually the case, mirrord 3.39.0 was not producing JSON errors.

**Comment by aviramha** [comment]
I think this is related to https://github.com/metalbear-co/mirrord/pull/1754
When targeting a deployment, it probably some of the times read the stderr and couldn't parse it.
Probably some race on what it reads first :q
